[workspace]
resolver = "3"
members = ["actual", "development", "db_engine"]

[patch.crates-io]
picoserve = { git = "https://github.com/sammhicks/picoserve.git", rev = "d68a535" }
leasehund = { path = "patches/leasehund" }
